services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pulsar-frontend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - PORT=3001
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend
    networks:
      - pulsar-network
    command: npm run dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pulsar-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URL=mongodb://mongodb:27017/pulsar
      - PORT=3000
      - JWT_SECRET=votre_secret_jwt_super_securise
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    depends_on:
      - mongodb
    networks:
      - pulsar-network
    command: npm run dev

  mongodb:
    image: mongo:latest
    container_name: pulsar-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - pulsar-network
    environment:
      - MONGO_INITDB_DATABASE=pulsar

  mongo-express:
    image: mongo-express
    container_name: pulsar-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongodb
    networks:
      - pulsar-network

networks:
  pulsar-network:
    driver: bridge

volumes:
  mongodb_data:
  frontend_node_modules:
  backend_node_modules: 